### ISSUE TITLE
Add qemu-guest-agent to kubevirt example

### ISSUE THREAD

**Issue by shi2wei3** [redhat-cop/rhel-bootc-examples#3]
@cgwalters Basic boot, reboot, most of info(including vnc console) on webUI works well without qemu-guest-agent, but to gain full experience qemu-guest-agent is required.
https://docs.openshift.com/container-platform/4.14/virt/virtual_machines/creating_vms_custom/virt-installing-qemu-guest-agent.html

**Comment by cgwalters** [comment]
Thanks for the report; PR in https://github.com/redhat-cop/rhel-bootc-examples/pull/4
